# Version: 0.1
# Name: base.grails2.4.3.run
FROM yan047/base.grails2.4.3:v1

MAINTAINER "boyan.au@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

# In case someone loses the Dockerfile
RUN rm -rf /etc/Dockerfile
ADD Dockerfile /etc/Dockerfile

RUN mkdir /etc/service/tomcatd
ADD tomcatstart.sh /etc/service/tomcatd/run

EXPOSE 8080
